import "./globals.css"; // Assuming this is a global CSS file for styles


import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Nav from "./(componets)/Nav";

config.autoAddCss = false;



export const metadata = {
  title: 'Ticket App',
  description: 'Generated by sahu',
};

// Define your layout component
export default function RootLayout({ children }) {
  return (
    <div className="flex flex-col h-screen max-h-screen">
      <Nav />
      <div className="flex-grow overflow-y-auto bg-page text-default-text">
        {/* Content area */}
        {children}
      </div>
    </div>
  );
}
